services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - 'ASPNETCORE_URLS=http://+:8080'
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__badgeur-api__Destinations__badgeur-api/destination1__Address=http://badgeur-backend:8080/
    depends_on:
      - badgeur-backend
    networks:
      - badgeur-network
    develop:
      watch:
        - action: sync+restart
          path: ./reverse-proxy
          target: /app
          ignore:
            - ./reverse-proxy/bin/
            - ./reverse-proxy/obj/

  badgeur-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - '8080'
    env_file:
      - ./backend/.env
    environment:
      - 'ASPNETCORE_URLS=http://+:8080'
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - badgeur-network
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
          ignore:
            - ./backend/bin/
            - ./backend/obj/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - 'REACT_APP_API_URL=http://localhost:8080'
    depends_on:
      - reverse-proxy
    networks:
      - badgeur-network
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /app
          ignore:
            - ./frontend/node_modules/
            - ./frontend/build/

networks:
  badgeur-network:
    driver: bridge