services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - 'ASPNETCORE_URLS=http://+:8080'
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__badgeur-api__Destinations__badgeur-api/destination1__Address=http://badgeur-backend:8080/
    depends_on:
      - badgeur-backend
    networks:
      - badgeur-network

  badgeur-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - '8080'
    environment:
      - 'ASPNETCORE_URLS=http://+:8080'
      - ASPNETCORE_ENVIRONMENT=Development
      - Supabase__Url=${SUPABASE_URL}
      - Supabase__Key=${SUPABASE_KEY}
      - Authentication__ValidIssuer=${SUPABASE_URL} 
      - Authentication__ValidAudience=authenticated
      - Authentication__JwtSecret=${JWT_SECRET}

    networks:
      - badgeur-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - 'REACT_APP_API_URL=http://localhost:8080'
    depends_on:
      - reverse-proxy
    networks:
      - badgeur-network 

networks:
  badgeur-network:
    driver: bridge