name: Docker-Compose - Dev Build

on:
  pull_request:
    branches: [ "preprod" ]
  push:
    branches: [ "preprod" ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the docker-compose
      working-directory: ./
      run: docker compose -f docker-compose.dev.yml build
    - name: Run the docker-compose
      working-directory: ./
      run: docker compose -f docker-compose.dev.yml up
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.dev.yml" down